name: fitween1
description: Firween Project Version 1

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  google_sign_in:
  get:
  image_picker:

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.0
  carousel_slider: ^4.1.1
  dots_indicator: ^2.1.0
  flutter_shake_animated: ^0.0.5
  grouped_list: ^5.1.2
  date_format: ^2.0.6
  intl: ^0.17.0
  table_calendar: ^3.0.6
  toggle_list: ^0.2.1
  google_fonts: ^3.0.1
  flutter_screenutil: ^5.5.3+2
  numberpicker: ^2.1.1
  fl_chart: ^0.55.0
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/alarm.png
    - assets/img/fitweenV1.png
    - assets/img/guest.png
    - assets/img/logo/apple.svg
    - assets/img/logo/fitween.svg
    - assets/img/logo/google.svg

fonts:
  - family: Noto_Sans_KR
    fonts:
      - asset: assets/font/Noto_Sans_KR/NotoSansKR-Black.otf
        weight: 900
      - asset: assets/font/Noto_Sans_KR/NotoSansKR-Bold.otf
        weight: 700
      - asset: assets/font/Noto_Sans_KR/NotoSansKR-Medium.otf
        weight: 500
      - asset: assets/font/Noto_Sans_KR/NotoSansKR-Regular.otf
        weight: 400
      - asset: assets/font/Noto_Sans_KR/NotoSansKR-Light.otf
        weight: 300
      - asset: assets/font/Noto_Sans_KR/NotoSansKR-Thin.otf
        weight: 200